### ISSUE TITLE
收集表信息时报错，怀疑表名或列名有MySQL关键字时出问题

### ISSUE THREAD

**Issue by jmbkeyes** [vipbooks/TableGo#2]
exception.TableGoException: exception.TableGoException: 收集表信息出错【当前表名: group，当前字段名:allowChooseLocker】: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group' at line 1
	at exception.TableGoException.newInstance(TableGoException.java:34) ~[TableGo.jar:?]
	at util.p.a(TableInfoUtils.java:96) ~[TableGo.jar:?]
	at a.b.a(DbWordBuilder.java:213) ~[TableGo.jar:?]
	at a.b.a(DbWordBuilder.java:189) ~[TableGo.jar:?]
	at ui.c.d.a(BuildDbDocumentDialogUI.java:366) ~[TableGo.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: exception.TableGoException: exception.TableGoException: 收集表信息出错【当前表名: group，当前字段名:allowChooseLocker】: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group' at line 1
	at exception.TableGoException.newInstance(TableGoException.java:34) ~[TableGo.jar:?]
	at util.i.b(MultiThreadUtils.java:209) ~[TableGo.jar:?]
	at util.p.a(TableInfoUtils.java:88) ~[TableGo.jar:?]
	... 4 more
Caused by: java.util.concurrent.ExecutionException: exception.TableGoException: 收集表信息出错【当前表名: group，当前字段名:allowChooseLocker】: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group' at line 1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:?]
	at util.i.b(MultiThreadUtils.java:198) ~[TableGo.jar:?]
	at util.p.a(TableInfoUtils.java:88) ~[TableGo.jar:?]
	... 4 more
Caused by: exception.TableGoException: 收集表信息出错【当前表名: group，当前字段名:allowChooseLocker】: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group' at line 1
	at exception.TableGoException.newInstance(TableGoException.java:34) ~[TableGo.jar:?]
	at util.p.a(TableInfoUtils.java:404) ~[TableGo.jar:?]
	at util.p.b(TableInfoUtils.java:86) ~[TableGo.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group' at line 1
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.8.0.jar:2.8.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.8.0.jar:2.8.0]
	at util.p.h(TableInfoUtils.java:1205) ~[TableGo.jar:?]
	at util.p.a(TableInfoUtils.java:224) ~[TableGo.jar:?]
	at util.p.b(TableInfoUtils.java:86) ~[TableGo.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more

**Comment by jmbkeyes** [comment]
看文档需要修改配置
